'use strict';
const assert=require('node:assert/strict');
const {normalizeDebate,sourceAnnotation,annotationChanged,validateEntry,speechParts}=require('../interface/app.js');
const guide=[{id:1,dimension:'Alinhamento Temático',indicators:['Focalizado','Periférico','Desalinhado']},{id:2,dimension:'Postura do Orador',indicators:['Técnica','Confiante','Agressiva','Emocional']},{id:3,dimension:'Credibilidade e Validação',indicators:['Referência Externa','Autoridade Própria','Recursos Retóricos']},{id:4,dimension:'Posicionamento',indicators:['Favorável','Contrário','Neutro','Ambíguo']}];
const original={debate_id:1,tema:'Tema',participantes:[{nome:'A',falas:[{id:'f1',texto:'😀abc',ordem_no_debate:1,taxonomia:{'Alinhamento Temático':['Focalizado']},resumo:'Resumo',propostas:[],interrupcoes:[{texto:'Aviso',participante:'B',apos_caractere_do_texto:1},{texto:'Sem posição',participante:'C',apos_caractere_do_texto:5}]}]}]};
const snapshot=JSON.stringify(original),view=normalizeDebate(original),row={person:'A',f:view.participantes[0].falas[0]};
assert.equal(JSON.stringify(original),snapshot);
assert.equal(speechParts(row.f).located.length,1);assert.equal(speechParts(row.f).unlocated.length,1);
assert.equal(Array.from(row.f.texto).slice(0,1).join(''),'😀');
const e={...sourceAnnotation(row.f,guide),fala_id:'f1',participante:'A',status:'revisado',decisao:'confirmado',agrupamento:'adequado',observacoes:'',validador:'Revisor',atualizado_em:new Date().toISOString()};
assert.equal(validateEntry(e,row,guide),e);
assert.throws(()=>validateEntry({...e,resumo:'Mudou'},row,guide),/alterados/);
assert.throws(()=>validateEntry({...e,validador:''},row,guide),/validador/);
assert.throws(()=>validateEntry({...e,decisao:'inconclusivo'},row,guide),/Descreva/);
assert.throws(()=>validateEntry({...e,participante:'B'},row,guide),/corresponde/);
assert.throws(()=>validateEntry({...e,taxonomia:{...e.taxonomia,'Posicionamento':['Favorável','Contrário']}},row,guide),/Indicadores/);
assert.throws(()=>validateEntry({...e,taxonomia:{...e.taxonomia,'Postura do Orador':['Inventado']}},row,guide),/Indicadores/);
assert.equal(validateEntry({...e,status:'rascunho',decisao:'',validador:''},row,guide).status,'rascunho');
assert.equal(validateEntry({...e,decisao:'corrigido',resumo:'Revisado'},row,guide).resumo,'Revisado');
assert.equal(validateEntry({...e,decisao:'inconclusivo',observacoes:'Titularidade incerta'},row,guide).decisao,'inconclusivo');
assert.equal(annotationChanged({...e,taxonomia:{...e.taxonomia,'Postura do Orador':['Técnica','Confiante']}},{...e,taxonomia:{...e.taxonomia,'Postura do Orador':['Confiante','Técnica']}},guide),false);
assert.throws(()=>normalizeDebate({...original,participantes:[...original.participantes,...original.participantes]}),/duplicado/);
const legacy={debate_id:1,tema:'Tema',participantes:[{nome:'A'}],transcricao:'Texto',turnos:[{id:'t1',inicio:0,fim:5}],falas:[{id:'f1',participante:'A',texto_titular:'Texto',turnos_titular:['t1'],ordem_inicio:1,interrupcoes:[{participante:'B',texto:'Aparte',apos_turno:'t1'}],anotacao:{dimensoes:{'Posicionamento':{indicadores:['Favorável']}},resumo:'Resumo',propostas:[{enunciado:'Medida'}]}}]};
const legacySnapshot=JSON.stringify(legacy),converted=normalizeDebate(legacy);
assert.equal(converted.participantes[0].falas.length,1);
assert.equal(converted.participantes[0].falas[0].texto,'Texto');
assert.equal(converted.participantes[0].falas[0].interrupcoes[0].apos_caractere_do_texto,5);
assert.deepEqual(converted.participantes[0].falas[0].propostas,['Medida']);
assert.equal(JSON.stringify(legacy),legacySnapshot);
console.log('Interface: integridade, compatibilidade, indicadores e decisões verificadas.');
